version: '3'
services:
  backend:
    image: node:16-alpine
    restart: always
    tty: true
    ports:
    - "3301:3301"
    volumes:
    - ./:/app/
    container_name: db_backend
    depends_on:
      - db
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todolistdb
    ports:
    - "3306:3306"
    volumes:
    - ./todolistdb_script.sql:/docker-entrypoint-initdb.d/todolistdb_script.sql